### PR TITLE
feat(destination): Implement webhook

### PR DESCRIPTION
**Pull request by iam-benyamin**

### CODE REVIEW

**Comment by mohsenHa** [comment]
I think we cannot convert `interface{}` or `any` to a specific type.

However, we can set `Integration. Config` to type `string` and store the JSON representation of the actual configuration in it. Then, we can convert the entire event object to JSON and pass it to RabbitMQ. On the worker side, we can decode the string back to the specific configuration type.

I write this example code:

```go
type Integration struct {
	ID             string
	SourceID       string
	Name           string
	Metadata       DestinationMetadata
	ConnectionType ConnectionType
	Enabled        bool
	Config         string
	CreatedAt      time.Time
}

wc := WebhookConfig{
		Headers: []Header{
			{
				Key:   "name",
				Value: "value",
			},
		},
		Payload: []Payload{
			{
				Key:   "name",
				Value: "value",
			},
		},
		Method: POSTWebhookMethod,
		URL:    "https://example.com",
	}
	wc_string, _ := json.Marshal(wc)

	fakeIntegration := entity.Integration{
		ID:       "10",
		SourceID: "1",
		Config:   string(wc_string),
		Metadata: entity.DestinationMetadata{
			ID:   "1",
			Name: "webhook",
			Slug: "webhook",
		},
	}
	// generate fake processedEvent
	pageName := "Home"
	pe := event.ProcessedEvent{
		SourceID:          "1",
		Integration:       fakeIntegration,
		MessageID:         "1",
		EventType:         "page",
		Name:              &pageName,
		Version:           1,
		SentAt:            time.Now(),
		ReceivedAt:        time.Now(),
		OriginalTimestamp: time.Now(),
		Timestamp:         time.Now(),
	}

	jpe, _ := json.Marshal(pe)
	fmt.Println(string(jpe))
	e, _ := taskentity.UnmarshalBytesToProcessedEvent(jpe)

	var pe2 WebhookConfig
	err := json.Unmarshal([]byte(e.Integration.Config), &pe2)
	if err != nil {
		fmt.Println("Error on unMarshaling config :", err)
	}
	fmt.Printf("%+v", pe2)
```
@iam-benyamin

**Comment by iam-benyamin** [comment]
Thank you for your suggestion

**Comment by iam-benyamin** [comment]
Could you check something effortlessly?

When I run the code last week, the event did not reach the handlers! could you check it too?

**Comment by gocastsian** [comment]
Please write `protobuf message` for processed event then you can use `oneOf` feature.
https://protobuf.dev/programming-guides/proto3/#using-oneof

**Pull request closed without merging**
