### PR TITLE
feat(issue #14): create logger package useing log/slog

### PR DESCRIPTION
**Pull request by AmirAtashghah**
I write logger package but , I don't know if I implemented it correctly or not

### CODE REVIEW

**Comment by gohossein** [comment]
Please add issue number to PR title like [these](https://github.com/ormushq/ormus/pull/17) PR.

**Comment by gohossein** [comment]
Please add unit test for logger package, use `logger_test` as package name for test files.

**Comment by AmirAtashghah** [comment]
i write test for logger package please check it.

**Comment by AmirAtashghah** [comment]
i add `New` function in logger package

**Pull request closed without merging**
